# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tarash Agarwas
firstname: Tarash
lastname: Agarwal
email: tarash.agarwal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lets build a new world on a click!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tarashagarwal.github.io" # the base hostname & protocol for your site
twitter_username: tarashagarwal
github_username:  tarashagarwal
twitter_url: https://twitter.com/tarashagarwal/
github_url:  https://github.com/tarashagarwal/

# Build settings
markdown: kramdown
